name: cit_238_app_states
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.2.0





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/music/Zico-NewThing.mp3
    - assets/music/bts-home.mp3
    - assets/music/bts-mikrokosmos.mp3
    - assets/music/bts-make_it_right.mp3



